BuildAll: ../Main/main.c ../Multiplayer/multiplayer.c ../Singleplayer/singleplayer.c ../General_Functions/generalfunctions.c ../Appearance_Functions/appearance.c
		gcc ../Main/main.c ../Multiplayer/multiplayer.c ../Singleplayer/singleplayer.c ../General_Functions/generalfunctions.c ../Appearance_Functions/appearance.c -o game.exe
		gcc ../Main/main.c ../Multiplayer/multiplayer.c ../Singleplayer/singleplayer.c ../General_Functions/generalfunctions.c ../Appearance_Functions/appearance.c -o game.out
